config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "planets#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :planets
  get 'bookings', to: 'bookings#my_bookings'
  get 'planets/:id/new', to: 'bookings#new', as: 'new_booking'
  post 'bookings', to: 'bookings#create'
  get 'bookings/:id/edit', to: 'bookings#edit'

  resources :bookings, only: %i[edit update destroy]


  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :planet

  validates :checkin, presence: true
  validates :checkout, presence: true
end

app/models/planet.rb
class Planet < ApplicationRecord
  belongs_to :user

  has_many :users, through: :bookings
  has_many :bookings
  has_one_attached :photo

  include PgSearch::Model
  pg_search_scope :search_by_name_address_and_description,
    against: [ :name, :address, :description ],
    using: {
      tsearch: { prefix: true }
  }

  validates :name, presence: true
  validates :address, presence: true
  validates :photo, presence: true
  validates :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :planets, dependent: :destroy
  has_many :planets, through: :bookings, dependent: :destroy

  has_many :bookings, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  def index
    @bookings = Booking.all
  end

  def my_bookings
    if current_user.nil?
      redirect_to new_user_session_path
      flash[:notice] = "Please Log In"
    else
      @bookings = Booking.where(user_id: current_user.id)
    end
  end

  def show
  end

  def new
    if current_user.nil?
      redirect_to new_user_session_path
      flash[:notice] = "Please Log In"
    else
      @planet = Planet.find(params[:id])
      @booking = Booking.new
    end
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.planet = Planet.find(params[:booking][:planet])
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @booking.update(booking_params)
    redirect_to bookings_path
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path, notice: "Planet was successfully destroyed."
  end

  private

  def booking_params
    params.require(:booking).permit(:checkin, :checkout)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  def index
    if params[:search].present? && !params[:search][:query].empty?
      @planets = Planet.search_by_name_address_and_description(params[:search][:query])
    elsif params[:search]
      @planets = Planet.all
    else
      @planets = Planet.all
    end
  end

  def show
    @planet = Planet.find(params[:id])
    @booking = Booking.new
  end

  def new
    if current_user.nil?
      redirect_to new_user_session_path
      flash[:notice] = "Please Log In"
    else
      @planet = Planet.new
    end
  end

  def create
    @planet = Planet.new(planet_params)
    @planet.user = current_user
    if @planet.save
      redirect_to planet_path(@planet)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @planet = Planet.find(params[:id])
  end

  def update
    @planet = Planet.find(params[:id])
    @planet.update(planet_params)
    redirect_to planet_path(@planet)
  end

  def destroy
    @planet = Planet.find(params[:id])
    @planet.destroy!
    redirect_to planets_path, notice: "Planet was successfully destroyed."
  end

  private

  def planet_params
    params.require(:planet).permit(:name, :address, :description, :photo, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class="form">
  <%= simple_form_for @booking do |f| %>
    <%= f.input :checkin, as: :string, input_html: {type: :date}%>
    <%= f.input :checkout, as: :string, input_html: {type: :date}%>
    <%= f.submit class:"btn btn-primary"%>
  <% end %>
</div>

app/views/bookings/my_bookings.html.erb
<div class="flex-wrapper">
  <div class="my-bookings-index">
  <br>
    <h1 style="color:white;"><strong>My Bookings</strong></h1>
    <ul>
    <% @bookings.each do |b| %>
      <div class="booking-ref">
        <div class ="planet-details">
          <%# <h3>Planet Name</h3> %>
          <h3><strong><%= b.planet.name %>, <%= b.planet.address.capitalize %></strong></h5>
        </div>
        <div class ="checkin-out">
          <h5><strong>Dates:</strong></h3>
          <%= b.checkin %>
          <br>to
          <br> <%= b.checkout %>
        </div>
          <%days = b.checkout - b.checkin %>
        <br>
        <%# <h3>Total Price</h3> %>
        <% if days.to_i == 1 %>
          <p><h5><strong>Total for <%= days.to_i %> day:</strong></h5>
          £<%= days.to_i * b.planet.price %></p>
        <% else %>
          <p><h5><strong>Total for <%= days.to_i %> days:</strong></h5> £<%= days.to_i * b.planet.price %></p>
        <% end %>
        <div class = buttons>
        <%= link_to "Edit Booking", edit_booking_path(b), class: "btn btn-light"   %>
        <%= link_to "Cancel", b, class: "btn btn-warning", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
        </div>
        <br>
        <br>
      </div>

    <% end %>
    </ul>
  </div>

app/views/bookings/new.html.erb
<div class="booking-new-form">
  <h1><strong>New Booking for <%= @planet.name %></strong></h1>
  <%= simple_form_for @booking do |b| %>
  <%= b.input :planet, :as => :hidden, :input_html => { :value => @planet.id } %>
  <%= b.input :checkin, as: :string, input_html: {type: :date}%>
  <%= b.input :checkout, as: :string, input_html: {type: :date}%>
  <%= b.button :submit, 'Book', class:"btn btn-primary" %>
  <% end %>
</div>

app/views/bookings/show.html.erb
<h1>hi</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Planbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="icon" type="image/png" href="../../assets/images/rocket-g40120ff65_1280.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class='<%= controller_name%>_<%=action_name %>_body'>

    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<%#= raise %>

app/views/planets/edit.html.erb
<div class="form">
  <%= simple_form_for (@planet) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :photo, as: :file %>
    <%= f.input :price %>
    <%= f.submit class:"btn btn-primary"  %>
    <% end %>
<br>
  <%= link_to "back to list", planets_path, class: "btn btn-light"   %>
</div>

app/views/planets/index.html.erb
<%# <div class="whole">
  <video autoplay muted loop class="banner">
    <source src="https://giant.gfycat.com/DifferentGiftedCoyote.mp4" type="video/mp4">
  </video>
</div>
  <div class="banner">
      <h1 class="name-banner">PLAN BNB</h1>
      <p class="name-banner">Experience of Planet</p>
  </div> %>

<%# <div id="videoDiv">
  <video id="video1" preload="" autoplay="" muted="" playsinline="" loop="">
    <source src= type="video/mp4">
  </video>
  <div id="videoMessage" class="styling">
    <h1>Plan BnB</h1>
    <p>Experience a new Planet</p>
  </div>
</div> %>

 <div class="flex-wrapper">
  <% if params[:search].nil? %>
    <div id="videowrapper">
      <div id="fullScreenDiv">
        <video id="video" role="presentation" preload="auto" playsinline="" crossorigin="anonymous" loop="" muted="" autoplay="" class="blur">
          <source src="https://giant.gfycat.com/DifferentGiftedCoyote.mp4" type="video/mp4">
        </video>

        <div id="videoMessage" class="styling d-grid">
        <div class="container"></div>
          <div>
            <h1>PLAN BNB</h1>
            <h2>Begin your intergalactic expedition <br>with the universe's first multiplanetary <br>bed & breakfast</h2>
          </div>
          <a class="ct-btn-scroll ct-js-btn-scroll" href="#cards"><img alt="Arrow Down Icon" src="https://www.solodev.com/assets/anchor/arrow-down.png"></a>

        </div>
      </div>
    </div>
  <% end %>

  <div class="container" id="cards" style="width: 90%;">

      <%# <h2 style="color:white;"><strong>Recently Uploaded</strong></h2> %>
      <br>
    <div class="planet-cards m-5">
      <% @planets.shuffle.each do |p| %>
      <div class='planet-card' onclick="this.querySelector('a').click(); return true;">
        <% if p.photo.attached? %>
            <%= cl_image_tag(p.photo.key)%>
          <% end %>


        <div class="planet-card-infos">
          <div>
            <h2> <%= link_to p.name, planet_path(p.id), class: "planetname" %> </h2>
          </div>
          <h2 class="planet-card-pricing">£ <%= p.price %> </h2>
        </div>
      </div>
    <% end %>
    </div>
  </div>
  </div>

app/views/planets/new.html.erb
<div class="form">
    <h1><strong>New Planet</strong></h1>
  <div class="container">
    <div>
      <%= simple_form_for (@planet), html: { class: "form-new-planet" } do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :description %>
        <%= f.input :photo, as: :file %>
        <%= f.input :price %>
        <%= f.submit   %>
      <% end %>
    </div>
    <br>
  </div>
    <%= link_to "Back To Index", planets_path(@planets), class: "btn btn-outline-dark"%>
</div>

app/views/planets/show.html.erb
<div class="showpage m-5">
  <div class="container mt-5">

    <h1 class="planet-title"><strong><%= @planet.name %></strong></h1>
      <div class="show-image-desc">
        <% if @planet.photo.attached? %>
        <%= cl_image_tag (@planet.photo.key) %>
        <% end %>
        <div class="p-3">
        <h6 class="text-start"><strong>Hosted by: <%= @planet.user.first_name %> <%= @planet.user.last_name %></strong></h6>

        <h6 class="text"><strong>Price per night: £<%= @planet.price%></strong></h6>
        <h6 class="text"><strong>Location: <%= @planet.address%></strong></h6>
        <p><%= @planet.description %></p>

      <% if current_user != @planet.user %>
        <div class="booking-new-form">
          <h1><strong>New Booking for <%= @planet.name %></strong></h1>
            <%= simple_form_for [@booking] do |b| %>
            <%= b.input :planet, :as => :hidden, :input_html => { :value => @planet.id } %>
            <%= b.input :checkin, as: :string, input_html: {type: :date}%>
            <%= b.input :checkout, as: :string, input_html: {type: :date}%>
            <%= b.button :submit, 'Book', class:"btn btn-primary" %>
            <% end %>
          <% end %>
        </div>
        </div>
      </div>

    <div class="show-page-button">
      <% if current_user && current_user == @planet.user %>
        <%= link_to "Delete Planet", @planet, class: "btn btn-danger", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
        <%= link_to "Edit planet", edit_planet_path, class: "btn btn-warning" %>
      <% end %>
      <%= link_to 'Back To Home', root_path(@planet), class: "btn btn-light" %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<div class="flash flash-warning alert alert-dismissible fade show" role="alert">
    <span><strong>Please Log In</span>
    <a data-bs-dismiss="alert" aria-label="Close">
       <i class="fas fa-times"></i>
    </a>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Plan bnb © 2022<i class="fas fa-heart"></i></div>
</div>